### ISSUE TITLE
Running into an issue with child routers using objects in the activeInstruction params, thereby causing "[object Object]" to be passed into activate method

### ISSUE THREAD

**Issue by nicmendoza** [BlueSpire/Durandal#556]
It seems that when I am using a child router, the params array on the activeInstruction includes objects in addition to strings, so when it joins them in router.loadUrl (router.js:508), and passes it to my widget's activate method, the url contains [object Object]

As an example, say I navigate to this url in my app:

view/person/19158/?interaction=87852&listId=17

where view is a route on the shell router that looks like "view*splat",
person is a route on a child router that looks like "person/:id*splat",
19158 is the id parameter,
and everything else is a query string

My widget's activate method is receiving the following arguments
    ["19158", "/[object Object]", {interaction: "87852",listId: "17"}]

I can just get the query params off of the third argument, but it seems like the second one is erroneous.

Would the following be an acceptable fix to guard against this? The only change is to line 508

    // starting at router.js:506
    if (router.relativeToParentRouter) {
        var instruction = this.parent.activeInstruction();
        coreFragment = instruction.params.filter(function(param){return typeof param === 'string'}).join('/');
    
        if (coreFragment && coreFragment.charAt(0) == '/') {
            coreFragment = coreFragment.substr(1);
        }
    
        if (!coreFragment) {
            coreFragment = '';
        }
    
        coreFragment = coreFragment.replace('//', '/').replace('//', '/');
    }

The above change causes the activate method to instead receive:
    ["19158", null, {interaction: "87852",listId: "17"}]

**Comment by davismj** [comment]
@davismj i will review this PR

**Comment by davismj** [comment]
it seems that this issue has already been resolved in the latest code base. in fact, the above behavior currently would pass
`["person/19158", { interaction: "87852", listId: "17" }]`
to the parent, and
`["19158", null, { interaction: "87852", listId: "17" }]`
to the child. This is the expected behavior. 

I have tested this behavior in the latest chrome, the latest ie, and emulated IE9. If you still see this issue after updating to the latest, please let us know and we'll grab some more details.

**Comment by EisenbergEffect** [comment]
Thanks for reviewing @davismj Closing now.
