### ISSUE TITLE
Could we pass a reason to the navigation cancelled event?

### ISSUE THREAD

**Issue by m90** [BlueSpire/Durandal#595]
When trying to navigate to a new route, but its activate hook rejects the promise (due to auth issues or sth else), all that the router gets notified of is `router:navigation:cancelled` with the handler being passed `instance, instruction, router`.

This leads to the problem that I can only tell the user that *something failed*.

Instead I'd like to do something like this in my viewmodels:

```js
this.activate = function(someParam){
  return myRepository.fetchData(someParam).then(function(data){
    return system.defer(function(dfd){
      // do some validation
      if (resultOk){
        dfd.resolve();
      } else {
        dfd.reject('Some reason the user might want to know about');
      }
    });
  });
};
```
Then I could go and do this somewhere else:
```js
router.on('router:navigation:cancelled', function(instance, instruction, router, error){
  // show error message to user
});
```

I already patched 2.0 in a way that this works, but recently updated to 2.1 and lost the feature again. As I'd like to steer clear of altering vendor code again (therefore making it part of my own codebase) I was thinking this might be a valuable addition to Durandal itself and might find its way into the framework as it does not conflict with any existing functionality.

I'd be happy to contribute this via a PR in the near future, but wanted to ask beforehand if I am missing something or if there is a way to achieve what I am looking for that I am not aware of.

**Comment by PWKad** [comment]
@m90 I think there are currently a few ways you could accomplish this without having to modify the source including some of the pub/sub capability or messaging.  Because this is such a large change in the fork that you referenced above I don't think we could merge it in without some serious tests in place to ensure that it was not going to affect existing 2.1 users.

@EisenbergEffect I would vote to close this one unless it gets some additional requests for the feature.

**Comment by m90** [comment]
@PWKad Thanks for having a look into that. While I agree with you regarding the fact that simply merging this is highly risky I think setting up a pubsub chain that will pass the error in parallel to the activation lifecycle isn't too good of an option as well. What's the point in using promises when you don't use their full potential?

**Comment by PWKad** [comment]
I agree that I just worried with how large the change would be :)

**Comment by EisenbergEffect** [comment]
I'm going to close this for now...I'm worried about there being unexpected consequences. @PWKad Can you investigate this for Aurelia's router. Is there an easy way to support this in the future? We might actually already, since this works differently in the new router...but I can't remember at the moment.
