### ISSUE TITLE
feature to use preloaded template in DOM

### ISSUE THREAD

**Issue by gogocat** [BlueSpire/Durandal#629]
It will be a feature is to make Durandal like Angular... when it do a template ajax call, it will check if there is a template in DOM first. If so, it will use it and stop the ajax call. 

This is useful when you want to render something on first load that is easier/cheap by using server side language. eg Razor view in .Net

**Comment by Craga89** [comment]
You can implement this using the existing framework by overidding each views `getView` method. For example, we're using Durandal with Jade views currently that we include as a direct dependency of the ViewModel:

We used CommonJS style modules in our app, so forgive the non-AMD style here:

```js
var ViewModel = require('base/viewModel');
var view = require('./view.html');
	
module.exports = ViewModel.extend({
	getView: function() {
		return view;
	}
});
```

**Comment by gogocat** [comment]
oh.. i didn't know there is a getView method... 
the change i made (and using in real projects) is intercepting text.js before making ajax call. 

https://github.com/gogocat/Sample-Durandal-preload-template

This way, everything in Durandal just work as normal. If there is a template in DOM, just use it otherwise make an ajax call, and Durandal internal cache will still work as expected.

**Comment by PWKad** [comment]
I think overall this is a great idea and would be a nice feature to include.  I think that development work from the team on Durandal.js will focus on any bug fixes or open issues for the next release.  Because this change is to the core of `text.js` we would have to find a separate way to build this change in to Durandal.js core or the build process instead which may be a decent amount of work.  If you felt very strongly I would suggest one of the two -

1. Performance benchmarks comparing before and after (that show a significant performance improvement :))
2. Packaging a PR that doesn't include modifying the text.js source, or augments it in a way that is not going to cause issues if someone wanted to update text.js to a newer version.

@EisenbergEffect I would vote to close this one.

**Comment by EisenbergEffect** [comment]
Agree. I'm closing this one for now. We don't want to modify text.js itself and any solution we do have, especially if it involves a custom plugin, should work correctly with the build process.

Keep in mind that the view locator can be configured today to use your own custom plugin. So, this is something that could be done without touching the core framework.
