### ISSUE TITLE
Alphabetize Website API

### ISSUE THREAD

**Issue by someyoungideas** [BlueSpire/Durandal#634]
Could all lists in the API Docs please be alphabetized? If there is a reason why not to do this that would be fine as well. If this code is accessible on GitHub I would be glad to create a pull request as well.

**Comment by PWKad** [comment]
@someyoungideas a PR would be nice but I think you need to update the step that builds out the data.json in the API pages on github - 

https://github.com/BlueSpire/Durandal/tree/gh-pages/api

This is done in the main project I believe in the build step in this power shell script - 

https://github.com/BlueSpire/Durandal/blob/master/build.ps1

So the adjustment would need to be so that the results are sorted somehow during that step.

**Comment by davismj** [comment]
I think he's requesting that the docs page, not the api docs page, be alphabetized. This is in a particular, logical order and should not be alphabetized. As @PWKad noted, the api docs are already in alphabetical order. @EisenbergEffect this can be closed.
