### ISSUE TITLE
Failed to load... errors in production

### ISSUE THREAD

**Issue by jignesh-dalal** [BlueSpire/Durandal#649]
Hi,

We are observing *few* occurrences of "Failed to load..." errors in our production (cloud) environment using Durandal 2.1.0 as follows:

1) Failed to load composed module (tmpl/shared/footer). Details: Script error for: tmpl/shared/footer\nhttp://requirejs.org/docs/errors.html#scripterror: at document path

2) Failed to load transition (transitions/entrance). Details: Script error for: transitions/entrance\nhttp://requirejs.org/docs/errors.html#scripterror: at document path

3) Failed to load composed module (tmpl/shared/header). Details: Script error for: tmpl/shared/header\nhttp://requirejs.org/docs/errors.html#scripterror: at document path

4) Failed to load routed module (tmpl/Coop/CoopLanding). Details: Script error for: tmpl/data/CoopLandingCache\nhttp://requirejs.org/docs/errors.html#scripterror: at document path

5) Failed to load routed module (tmpl/home/landing). Details: Script error for: tmpl/home/landing\nhttp://requirejs.org/docs/errors.html#scripterror: at document path

We haven't found much information pertaining to these issues. Any ideas/suggestions/pointers on what could be causing these errors?

**Comment by leftclickben** [comment]
It looks like you're running the `r.js` optimizer for production deployments, but you have a couple of configuration issues:

1. You have to explicitly include plugins and transitions that you are using, in the `include` option.  This is because they are loaded dynamically, not through a direct call to `require` or `define`, so the optimizer doesn't know to include them if you don't explicitly list them.
2. You have to include both `**/*.js` and `**/*.html` in the `src` option, otherwise you won't have the templates.

(I'm not a Durandal maintainer btw, I'm just a developer who uses the framework so I'm subscribed to notifications and this problem looked familiar to me).

**Comment by jignesh-dalal** [comment]
No we are not running the `r.js` optimizer; instead we use web essentials to optimize the files and load/include them in the package based on build configuration i.e. `debug\release`.

**Comment by jignesh-dalal** [comment]
closed by mistake

**Comment by davismj** [comment]
@jignesh-dalal nothing pops out to me here, but i have a few ideas of what might be going on. this is probably not an issue with durandal though. please send me a message on gitter and i will try to help you work through this issue if you're still having it.

@EisenbergEffect this can probably be closed. we can reopen it if it really is a durandal issue.
