### ISSUE TITLE
Composition depends on observables accessed in the activate callback of the model

### ISSUE THREAD

**Issue by Andrey-Gusakov** [BlueSpire/Durandal#658]
I have an issue with composition, it seems similar to #568. The behavior is really odd, I'm not sure if the problem was understood correctly in the #568 thread. Or perhaps I have a different one.

Consider the following code
![2015-05-12_1714](https://cloud.githubusercontent.com/assets/10154965/7589285/5f5f9566-f8ca-11e4-9be1-f3372e738a96.png)

The parent.js is on the router and it has the child composition(via compose binding). Most of the time it is an object of ChildViewModelOne, except the case when the token is 'baz'. There are no observables in my compose binding, so only thing that can re-evaluate my child composition is changing of the route(i.e. navigation '/parent/foo' -> '/parent/bar'). But point is it gets dependency on someObservable in my child viewmodel. That is, any time the someObservable changes, it triggers the entire child composition to re-evaluate. It happens when the childComposition object stays the same during navigation around parent.js.

My guess is the following.
The composition binding essentially is a computed. Evaluation process subscribes binding to all observables that are being accessed during that process. There are many places during "update" callback in composition binding where the call stack is cut, I mean the deferred functions are put in queue and the compose binding finishes its evaluation. When the deferred functions are resolved in the future they are not in the context of computed observable any more, so accessing to observables are not considered as a dependencies of binding. But when I navigate around the same module, the view for ChildViewModelOne is cached, and deferred functions are resolved right away. That cause the call of activate callback to be in the context of computed observable(binding), therefore accessing to observables in the activate callback causes compose binding to depend on inner observables of the model.

The presented code is just a demo to show the problem. Sorry for long explanation.

**Comment by navels** [comment]
What happens if you move the code that operates on your observables out of activate() and into bindingComplete()?

**Comment by Andrey-Gusakov** [comment]
Actually, I did put a workaround. I cut the call stack before calling activate callback with setTimeout(0), because currently we use knockout 3.2.
Moving code to bindingComplete would work if the activate returned the promise(not my case). Moving to compositionComplete works. But I think it wouldn't work for the last composition in chain, since it calls all compositionComplete callbacks on zeroing counter. Hmm... It seems the last composition will take the dependencies on all observables that are accessed in the compositionComplete callbacks.

Either way, I've already applied workaround. I posted that because I think it is framework's bug.

**Comment by Andrey-Gusakov** [comment]
Pull request: #659

**Comment by navels** [comment]
+1

**Comment by Oleg-Tamarintsev** [comment]
+1

**Comment by maca89** [comment]
+1!

**Comment by jkjome** [comment]
The suggested fix resolved my issue.  I have a view/viewModel that applies focus() to the first element with an autofocus attribute upon attached().  When the focused element gets focused, it toggles a 'selected' knockout observable to true.  But then the page is unresponsive.  Any tabs or clicks result in merely re-firing binding().  No functions actually get fired upon clicking buttons.  The page only becomes responsive after I unfocus the browser window and then come back to it.  The following remedies resolve the issue...

1. Removing focus() in attached() - not acceptable - we need to focus
2. Moving focus() to compositionComplete() - feasible for this viewModel, but it is common throughout the app to do this in attached() (among a few other things done upon attached()), and there's no good reason to have to change since...
3. Our code works fine as written if we use Andrey-Gusakov's fix of wrapping the "tryActivate" function with "ko.ignoreDependencies()" in compose.js within the "bindAndShow" function.

How Durandal 2.2.0 was released without including this fix is beyond me?  In fact, it seems like there might be a few other reported issues it might fix.  Please release a 2.2.1 with this fix in place!

**Comment by davismj** [comment]
@EisenbergEffect I've taken a look at the change. It's simple enough and seems like a reasonable change. Though I've not tried the code, based on the feedback of trusted community members, I recommend we pull this in. What do you think?

**Comment by EisenbergEffect** [comment]
Merged.
